ref(controller): Apply C-CUSTOM-TYPE to set_io_attached
main--/windows-gaming pull request #48
Opened 2017-05-19 14:51 UTC by oberien

2017-05-20 23:18 UTC, main-- requested changes

2017-05-20 23:18 UTC, main-- commented on windows-gaming-driver/src/controller.rs
> +    pub fn io_force_attach(&mut self) {
Why does this even exist? Just put the attach code here and call this from `io_attach`. This pattern is quite obvious and very common.

2017-05-20 23:18 UTC, main-- commented on windows-gaming-driver/src/controller.rs
> +            _ => self.detach()
Same here, there's no reason to hide the functionality in a private method.

Also, `assert!(self.ga != State::Suspending)` feels **much** more natural than a match here.

2017-05-21 06:14 UTC, oberien commented
Done

2017-05-21 19:25 UTC, main-- approved these changes

2017-05-21 19:25 UTC, merged