Making it pretty
main--/windows-gaming pull request #52
Opened 2017-05-25 18:06 UTC by main--

btw very nice about yaml is that it supports hex (for device IDs)

2017-05-26 08:49 UTC, oberien requested changes
I personally prefer toml over yaml, but /shrug. How does yaml solve that optionals are not shown in the config file in toml? Does it support tuples?

I like the idea of making the sound config part of windows-gaming. Unfortunately that won't make it work on my end ;)

Please update the default config in `misc` to reflect our latest config state with yaml.

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +    ByPort { bus: u16, port: u16 },
Create a new struct `ByPort` or `UsbPort` or so and make the variant `ByPort(UsbPoirt)`. While struct variants in enums are fine for matching, you can't write a function which takes it as argument and you can't use it in a generic context.

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +    Alsa {
extract struct

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +    PulseAudio {
dito

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +
interesting newline

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +
dito

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +    pub fn load<P: AsRef<Path>>(path: P) -> Option<Config> {
If implementing config migration, we should do so properly. We will definitely need automatic config migration at some point, so why not do it now? :)

I'd suggest adding a "version" property to the config file. We should first read the version property if possiblea as struct having only that one property, or parse the config file as `Value` and manually extract the "version" information. We should create a new mod containing one function which reads the version and calls all proper upgrade functions, which are in (different) mods: `config/mod.rs` contains all current config stuff. Either `config/version.rs` or `config/version/mod.rs` contains the main upgrade function and either `config/version/version{1,2,…}.rs` or `config/version{1,2,…}.rs` contain the functions to upgrade from the previous to that version.

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/controller.rs
> +                    if attr.name() == "busnum" {
`match attr.name()`?

2017-05-26 08:49 UTC, oberien commented on windows-gaming-driver/src/controller.rs
> +    return match scanner.next() {
why `return match … { … };`?

2017-05-26 09:26 UTC, main-- commented on windows-gaming-driver/src/config.rs
> +    ByPort { bus: u16, port: u16 },
I know that and I don't care. It's fine like this. We never need to pass this around.

2017-05-26 09:26 UTC, main-- commented on windows-gaming-driver/src/config.rs
> +    Alsa {
~

2017-05-26 09:26 UTC, main-- commented on windows-gaming-driver/src/config.rs
> +    PulseAudio {
~

2017-05-26 09:27 UTC, main-- commented on windows-gaming-driver/src/config.rs
> +
The name is conceptually different from all the other things.

2017-05-26 09:36 UTC, main-- commented on windows-gaming-driver/src/config.rs
> +    pub fn load<P: AsRef<Path>>(path: P) -> Option<Config> {
How about no? This sure seems like a smart idea ... until you realize that you basically have to fully duplicate the entire config code for every single version plus conversion code that doesn't even make sense in many corner cases (you had no PCI slots? well yeah good luck finding them).

Honest guess is something around 10x the code for config? And around 20x the work as we can no longer just (de)serialize and be done?

And what do we gain? A user base of virtually no one no longer has to deal with breaking changes to the config of a v0.1 tool.

The proper solution is to just not have any breaking changes. But it doesn't matter right now as we don't have a stable release anyways.

Sure I'm not opposed to doing it like this but I won't be the one developing **and maintaining** it.

2017-05-26 09:36 UTC, main-- commented on windows-gaming-driver/src/controller.rs
> +    return match scanner.next() {
literally says that in the line above

2017-05-26 09:38 UTC, main-- commented on windows-gaming-driver/src/controller.rs
> +                    if attr.name() == "busnum" {
doesn't work here, it's an `OsStr`

2017-05-26 09:46 UTC, main-- commented
>How does yaml solve that optionals are not shown in the config file in toml?

AFAICS it doesn't (kind-of): `setup: ~` is what I got in my config. But I'm fine with that.

>Does it support tuples?

no idea, probably. but we don't need that now anyways

>Please update the default config in misc to reflect our latest config state with yaml.

not sure I'm lazy - only one who needs this is you guys and why bother when I can just tell you / send you mine

In the big picture, you're not supposed to need this anyways. The file in `misc` is a remnant from a time when you were supposed to set this up by creating the config file, wizard wasn't even an idea. We might decide to write a config reference anyways but should do it properly then (fully document).

2017-05-26 16:19 UTC, oberien commented
¯\\_(ツ)_/¯

2017-05-26 16:19 UTC, oberien approved these changes

2017-05-27 06:23 UTC, oberien requested changes
I do need the structs to be actual structs and not an enum variant ;) At least the `UsbBinding::ByPort` one.

2017-05-27 15:41 UTC, merged