PoC
main--/windows-gaming pull request #92
Opened 2017-06-17 15:29 UTC by main--

2017-06-17 16:09 UTC, oberien requested changes
I mean, this needs hella fixing before it's able to be merged.

2017-06-17 16:09 UTC, oberien commented on windows-gaming-driver/src/driver/libinput.rs
> +    let fd = open(x, y);
Why not use `fs::open` and `AsRawFd`? We'll need to `mem::forget` the `File` and use `FromRawFd` in `do_close` to properly drop the file. Still, this is definitely more rusty.

2017-06-17 16:09 UTC, oberien commented on windows-gaming-driver/src/driver/libinput.rs
> +pub struct InputListener<'a>(pub &'a RefCell<Input>);
Does the internal value actually need to be public?

2017-06-17 16:09 UTC, oberien commented on windows-gaming-driver/src/driver/monitor/codec.rs
> +        axis: &'static str,
Make an enum out of it.

2017-06-17 16:12 UTC, main-- commented on windows-gaming-driver/src/driver/libinput.rs
> +pub struct InputListener<'a>(pub &'a RefCell<Input>);
sure or else you can't construct it

2017-06-17 16:12 UTC, main-- commented on windows-gaming-driver/src/driver/monitor/codec.rs
> +        axis: &'static str,
if only we had a tool that could autogenerate these definitions :thinking:

2017-06-17 16:12 UTC, main-- commented on windows-gaming-driver/src/driver/libinput.rs
> +    let fd = open(x, y);
I disagree

what we really want here is a raw file descriptor

we are already in C land, there's no point in trying to act like this is rust code

2017-06-17 17:18 UTC, oberien commented on windows-gaming-driver/src/driver/monitor/codec.rs
> +        axis: &'static str,
That'd be pretty damn fancy, that's true :thonkin:

2017-06-21 23:04 UTC, main-- commented on windows-gaming-driver/src/driver/mod.rs
> +                    ]).take(steps.abs() as usize).collect(),
bug

2017-07-18 06:45 UTC, main-- commented
fwiw there's a [patch](https://lists.freedesktop.org/archives/wayland-devel/2017-July/034500.html) for libinput now

2017-07-18 16:40 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +
¿

2017-07-21 20:27 UTC, main-- commented on windows-gaming-driver/src/driver/hotkeys/linux.rs
> +const KEY_MEDIASTOP: u32 = 166;
correct names would be

```
#define KEY_NEXTSONG		163
#define KEY_PLAYPAUSE		164
#define KEY_PREVIOUSSONG	165
#define KEY_STOPCD		166
```

*shrug*

2017-07-21 20:30 UTC, main-- commented on windows-gaming-driver/src/driver/hotkeys/linux.rs
> +const KEY_MEDIASTOP: u32 = 166;
@oberien correct names would be

```
#define KEY_NEXTSONG		163
#define KEY_PLAYPAUSE		164
#define KEY_PREVIOUSSONG	165
#define KEY_STOPCD		166
```

*shrug*

2017-07-21 20:39 UTC, moritzuehling submitted a review, later dismissed

2017-07-21 20:39 UTC, moritzuehling commented on windows-gaming-driver/src/driver/controller.rs
> +    LightFallback,
Consider renaming this to something `LightAwaitingUpgrade` to better describe what it does.

2017-07-21 20:39 UTC, moritzuehling commented on windows-gaming-driver/src/driver/controller.rs
> +                self.light_attach();
A notification for the user seems to be approperiate here. 

It is a fallback, so the user ought to know about it

2017-07-21 20:39 UTC, moritzuehling commented on windows-gaming-driver/src/driver/hotkeys/keys.rs
> +pub enum Keys {
Should be "Kies"

2017-07-21 20:50 UTC, oberien requested changes

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/config.rs
> +
¿ still

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/controller.rs
> +                        (&self.monitor).send(QmpCommand::DeviceDel { id: format!("usb{}", i) }).unwrap();
Weird indentation, would have done it the other way around (indent .filter more).

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/hotkeys/mod.rs
> +        (self.modifiers.iter().fold(base, |sum, &x| sum | (x as u32)), self.key as u32)
Please add curly parenthesis around `sum | (x as u32)` to distinguish it from the closure-arguments.

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/libinput.rs
> + */
Still needed?

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/mod.rs
> +    let (mut input, input_events) = libinput::Input::new(&handle, cfg.machine.usb_devices.clone());
![](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/mod.rs
> +        use input::event::keyboard::{KeyState, KeyboardEventTrait};
welp

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/qemu.rs
> +            debug!("usb-mouse at xhci{}.0p{}", port / usable_ports, (port % usable_ports) + 1);
If it's stupid, but it works, it ain't stupid.

2017-07-21 20:50 UTC, oberien commented on windows-gaming-driver/src/driver/mod.rs
> +    }).forward(monitor_sender.sink_map_err(|_| ())).then(|_| Ok(()));
Could you please try to inline all mods into this file?

2017-07-21 20:57 UTC, oberien commented on windows-gaming-driver/src/driver/hotkeys/linux.rs
> +const KEY_MEDIASTOP: u32 = 166;
Done

2017-07-21 22:05 UTC, oberien approved these changes

2017-07-21 22:21 UTC, merged